name: Synchronize the packages

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 * * * *'

jobs:
  synchronize:
    name: Synchronize from github releases
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Run the synchronizer
        run: |
          for i in ghostty-org/ghostty
          do
            bash synchronizer.sh "$i"
          done
      -
        name: Synchronize iTerm2
        run: |
          curl -o iTerm -LO https://iterm2.com/downloads/stable/latest
      - 
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'Update triggered from the GA'
